spring:
        datasource:
                drive-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3300/spring_board
                username: root
                password: 1234
        jpa:
                database: mysql
                database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
                generate-ddl: true
                hibernate:
                        ddl-auto: update
                show_sql: true
logging:
        level:
# log.error로그 이상만 출력 : Trace < debug < info < error
# 실무에서는 일반적으로 info로 설정, info는 굳이 설정 안 해도 default가 info
                root: info